[package]
name = "transitive"
version = "0.4.0"
edition = "2021"
authors = ["bobozaur"]
description = "Transitive derive macros for Rust."
license = "MIT"
repository = "https://github.com/bobozaur/transitive"
keywords = ["transitive", "macros", "rust"]
exclude = ["tests/*"]
categories = ["macros"]

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.51"
quote = "1.0.23"
syn = "1.0.107"