name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly

      - name: Check format
        run: cargo +nightly fmt --check

  clippy:
    name: Clippy
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.77.0
      - uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --tests
        env:
          RUSTFLAGS: -D warnings

  tests:
    name: Tests
    needs: clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.77.0
      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test
